const express = require("express");
const prisma = require('../config/prisma');
const generateSignedUrl = require("../services/s3Download.service");

const router = express.Router();

// GET /api/documents/related/:relatedId
router.get("/related/:relatedId", async (req, res, next) => {
    try {
        let searchId = req.params.relatedId;

        // Check if the provided ID is a public Application ID format (e.g. APP-2026-...)
        if (searchId.startsWith('APP-')) {
            const connection = await prisma.connectionApplication.findUnique({
                where: { applicationId: searchId },
                select: { id: true }
            });
            if (connection) searchId = connection.id;
        }
        // Check if it's a public Complaint ID format (e.g. CMP-...)
        else if (searchId.startsWith('CMP-')) {
            const complaint = await prisma.complaint.findUnique({
                where: { complaintNumber: searchId }, // Assuming complaintNumber is unique
                select: { complaintId: true }
            });
            // Also try by complaintId if complaintNumber fails, or handle differently if needed
            if (complaint) searchId = complaint.complaintId;
        }

        const documents = await prisma.document.findMany({
            where: { relatedId: searchId }
        });

        if (!documents || documents.length === 0) {
            return res.json({ success: true, documents: [] });
        }

        // Generate signed URLs for all documents
        const docsWithUrls = await Promise.all(
            documents.map(async (doc) => ({
                documentId: doc.documentId,
                documentType: doc.documentType,
                fileName: doc.fileName,
                url: await generateSignedUrl(doc.filePath, doc.fileName)
            }))
        );

        res.json({
            success: true,
            documents: docsWithUrls
        });
    } catch (err) {
        console.error("Document related fetch error:", err);
        next(err);
    }
});

/**
 * GET /api/documents/citizen/:citizenId
 * Returns all documents generated by a specific citizen
 */
router.get("/citizen/:citizenId", async (req, res, next) => {
    try {
        const { citizenId } = req.params;
        const { department } = req.query;

        const whereClause = { citizenId };
        if (department) {
            whereClause.department = department;
        }

        const documents = await prisma.document.findMany({
            where: whereClause,
            orderBy: { uploadedAt: 'desc' }
        });

        if (!documents || documents.length === 0) {
            return res.json({ success: true, documents: [] });
        }

        // Generate signed URLs for all documents
        const docsWithUrls = await Promise.all(
            documents.map(async (doc) => ({
                documentId: doc.documentId,
                documentType: doc.documentType,
                relatedEntity: doc.relatedEntity,
                relatedId: doc.relatedId,
                fileName: doc.fileName,
                createdAt: doc.uploadedAt,
                url: await generateSignedUrl(doc.filePath, doc.fileName)
            }))
        );

        res.json({
            success: true,
            documents: docsWithUrls
        });
    } catch (err) {
        console.error("Citizen Document fetch error:", err);
        next(err);
    }
});

/**
 * GET /api/documents/:documentId
 * Returns a signed download URL for the document
 */
router.get("/:documentId", async (req, res, next) => {
    try {
        const { documentId } = req.params;

        const document = await prisma.document.findUnique({
            where: { documentId }
        });

        if (!document) {
            return res.status(404).json({
                success: false,
                error: {
                    code: "NOT_FOUND",
                    message: "Document not found"
                }
            });
        }

        const signedUrl = await generateSignedUrl(document.filePath, document.fileName);

        res.json({
            success: true,
            documentId: document.documentId,
            fileName: document.fileName,
            url: signedUrl
        });

    } catch (err) {
        console.error("Document download error:", err);
        next(err);
    }
});

module.exports = router;
