const express = require("express");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
const generateSignedUrl = require("../services/s3Download.service");

const router = express.Router();

// GET /api/documents/related/:relatedId
router.get("/related/:relatedId", async (req, res, next) => {
    try {
        const { relatedId } = req.params;

        const documents = await prisma.document.findMany({
            where: { relatedId }
        });

        if (!documents || documents.length === 0) {
            return res.json({ success: true, documents: [] });
        }

        // Generate signed URLs for all documents
        const docsWithUrls = await Promise.all(
            documents.map(async (doc) => ({
                documentId: doc.documentId,
                documentType: doc.documentType,
                fileName: doc.fileName,
                url: await generateSignedUrl(doc.filePath)
            }))
        );

        res.json({
            success: true,
            documents: docsWithUrls
        });
    } catch (err) {
        console.error("Document related fetch error:", err);
        next(err);
    }
});

/**
 * GET /api/documents/citizen/:citizenId
 * Returns all documents generated by a specific citizen
 */
router.get("/citizen/:citizenId", async (req, res, next) => {
    try {
        const { citizenId } = req.params;
        const { department } = req.query;

        const whereClause = { citizenId };
        if (department) {
            whereClause.department = department;
        }

        const documents = await prisma.document.findMany({
            where: whereClause,
            orderBy: { uploadedAt: 'desc' }
        });

        if (!documents || documents.length === 0) {
            return res.json({ success: true, documents: [] });
        }

        // Generate signed URLs for all documents
        const docsWithUrls = await Promise.all(
            documents.map(async (doc) => ({
                documentId: doc.documentId,
                documentType: doc.documentType,
                relatedEntity: doc.relatedEntity,
                relatedId: doc.relatedId,
                fileName: doc.fileName,
                createdAt: doc.uploadedAt,
                url: await generateSignedUrl(doc.filePath)
            }))
        );

        res.json({
            success: true,
            documents: docsWithUrls
        });
    } catch (err) {
        console.error("Citizen Document fetch error:", err);
        next(err);
    }
});

/**
 * GET /api/documents/:documentId
 * Returns a signed download URL for the document
 */
router.get("/:documentId", async (req, res, next) => {
    try {
        const { documentId } = req.params;

        const document = await prisma.document.findUnique({
            where: { documentId }
        });

        if (!document) {
            return res.status(404).json({
                success: false,
                error: {
                    code: "NOT_FOUND",
                    message: "Document not found"
                }
            });
        }

        const signedUrl = await generateSignedUrl(document.filePath);

        res.json({
            success: true,
            documentId: document.documentId,
            fileName: document.fileName,
            url: signedUrl
        });

    } catch (err) {
        console.error("Document download error:", err);
        next(err);
    }
});

module.exports = router;
